# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ivan Kulagin
tagline:          "Kulagin's Website"
description:      "Ivan Kulagin's Website"
url:              http://ikulagin.github.io
rss:              atom.xml

author:
  name:           'Ivan Kulagin'
  url:            http://ikulagin.github.io
  ava_sidebar:    "ava_sidebar.jpg"
  ava_home:       "ava_home.jpg"
  word_cloud:      "word_cloud.jpg"
  github:         "Ikulagin"
  email:          "ivan.i.kulagin@gmail.com"
  skype:          "ivan_dizel"
  slideshare:     "http://www.slideshare.net/ivankulagin1"
  vk:             "https://vk.com/id4057191"
  facebook:       "https://www.facebook.com/ivan.kulagin.1"

paginate:         3
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]

# Custom vars
version:          1.0.0

github:
    repo:           https://github.com/Ikulagin/ikulagin.github.io
